# CMAKE generated file: DO NOT EDIT!
# Generated by "MSYS Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /D/Windows_Programs/CMake/bin/cmake.exe

# The command to remove a file.
RM = /D/Windows_Programs/CMake/bin/cmake.exe -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /D/Apps/jsoncompress-c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /D/Apps/jsoncompress-c

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/D/Windows_Programs/CMake/bin/cmake-gui.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/D/Windows_Programs/CMake/bin/cmake.exe -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /D/Apps/jsoncompress-c/CMakeFiles /D/Apps/jsoncompress-c/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /D/Apps/jsoncompress-c/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named jsoncompress

# Build rule for target.
jsoncompress: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 jsoncompress
.PHONY : jsoncompress

# fast build rule for target.
jsoncompress/fast:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/build
.PHONY : jsoncompress/fast

src/CMemLeak.obj: src/CMemLeak.c.obj

.PHONY : src/CMemLeak.obj

# target to build an object file
src/CMemLeak.c.obj:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/CMemLeak.c.obj
.PHONY : src/CMemLeak.c.obj

src/CMemLeak.i: src/CMemLeak.c.i

.PHONY : src/CMemLeak.i

# target to preprocess a source file
src/CMemLeak.c.i:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/CMemLeak.c.i
.PHONY : src/CMemLeak.c.i

src/CMemLeak.s: src/CMemLeak.c.s

.PHONY : src/CMemLeak.s

# target to generate assembly for a file
src/CMemLeak.c.s:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/CMemLeak.c.s
.PHONY : src/CMemLeak.c.s

src/json-compress/json-compress.obj: src/json-compress/json-compress.c.obj

.PHONY : src/json-compress/json-compress.obj

# target to build an object file
src/json-compress/json-compress.c.obj:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/json-compress/json-compress.c.obj
.PHONY : src/json-compress/json-compress.c.obj

src/json-compress/json-compress.i: src/json-compress/json-compress.c.i

.PHONY : src/json-compress/json-compress.i

# target to preprocess a source file
src/json-compress/json-compress.c.i:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/json-compress/json-compress.c.i
.PHONY : src/json-compress/json-compress.c.i

src/json-compress/json-compress.s: src/json-compress/json-compress.c.s

.PHONY : src/json-compress/json-compress.s

# target to generate assembly for a file
src/json-compress/json-compress.c.s:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/json-compress/json-compress.c.s
.PHONY : src/json-compress/json-compress.c.s

src/json-compress/json-decompress.obj: src/json-compress/json-decompress.c.obj

.PHONY : src/json-compress/json-decompress.obj

# target to build an object file
src/json-compress/json-decompress.c.obj:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/json-compress/json-decompress.c.obj
.PHONY : src/json-compress/json-decompress.c.obj

src/json-compress/json-decompress.i: src/json-compress/json-decompress.c.i

.PHONY : src/json-compress/json-decompress.i

# target to preprocess a source file
src/json-compress/json-decompress.c.i:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/json-compress/json-decompress.c.i
.PHONY : src/json-compress/json-decompress.c.i

src/json-compress/json-decompress.s: src/json-compress/json-decompress.c.s

.PHONY : src/json-compress/json-decompress.s

# target to generate assembly for a file
src/json-compress/json-decompress.c.s:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/json-compress/json-decompress.c.s
.PHONY : src/json-compress/json-decompress.c.s

src/main.obj: src/main.c.obj

.PHONY : src/main.obj

# target to build an object file
src/main.c.obj:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/main.c.obj
.PHONY : src/main.c.obj

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/main.c.s
.PHONY : src/main.c.s

src/parse-json/helpers.obj: src/parse-json/helpers.c.obj

.PHONY : src/parse-json/helpers.obj

# target to build an object file
src/parse-json/helpers.c.obj:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/parse-json/helpers.c.obj
.PHONY : src/parse-json/helpers.c.obj

src/parse-json/helpers.i: src/parse-json/helpers.c.i

.PHONY : src/parse-json/helpers.i

# target to preprocess a source file
src/parse-json/helpers.c.i:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/parse-json/helpers.c.i
.PHONY : src/parse-json/helpers.c.i

src/parse-json/helpers.s: src/parse-json/helpers.c.s

.PHONY : src/parse-json/helpers.s

# target to generate assembly for a file
src/parse-json/helpers.c.s:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/parse-json/helpers.c.s
.PHONY : src/parse-json/helpers.c.s

src/parse-json/json-node-ptr-list.obj: src/parse-json/json-node-ptr-list.c.obj

.PHONY : src/parse-json/json-node-ptr-list.obj

# target to build an object file
src/parse-json/json-node-ptr-list.c.obj:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/parse-json/json-node-ptr-list.c.obj
.PHONY : src/parse-json/json-node-ptr-list.c.obj

src/parse-json/json-node-ptr-list.i: src/parse-json/json-node-ptr-list.c.i

.PHONY : src/parse-json/json-node-ptr-list.i

# target to preprocess a source file
src/parse-json/json-node-ptr-list.c.i:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/parse-json/json-node-ptr-list.c.i
.PHONY : src/parse-json/json-node-ptr-list.c.i

src/parse-json/json-node-ptr-list.s: src/parse-json/json-node-ptr-list.c.s

.PHONY : src/parse-json/json-node-ptr-list.s

# target to generate assembly for a file
src/parse-json/json-node-ptr-list.c.s:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/parse-json/json-node-ptr-list.c.s
.PHONY : src/parse-json/json-node-ptr-list.c.s

src/parse-json/json-parser.obj: src/parse-json/json-parser.c.obj

.PHONY : src/parse-json/json-parser.obj

# target to build an object file
src/parse-json/json-parser.c.obj:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/parse-json/json-parser.c.obj
.PHONY : src/parse-json/json-parser.c.obj

src/parse-json/json-parser.i: src/parse-json/json-parser.c.i

.PHONY : src/parse-json/json-parser.i

# target to preprocess a source file
src/parse-json/json-parser.c.i:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/parse-json/json-parser.c.i
.PHONY : src/parse-json/json-parser.c.i

src/parse-json/json-parser.s: src/parse-json/json-parser.c.s

.PHONY : src/parse-json/json-parser.s

# target to generate assembly for a file
src/parse-json/json-parser.c.s:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/parse-json/json-parser.c.s
.PHONY : src/parse-json/json-parser.c.s

src/parse-json/stringbuilder.obj: src/parse-json/stringbuilder.c.obj

.PHONY : src/parse-json/stringbuilder.obj

# target to build an object file
src/parse-json/stringbuilder.c.obj:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/parse-json/stringbuilder.c.obj
.PHONY : src/parse-json/stringbuilder.c.obj

src/parse-json/stringbuilder.i: src/parse-json/stringbuilder.c.i

.PHONY : src/parse-json/stringbuilder.i

# target to preprocess a source file
src/parse-json/stringbuilder.c.i:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/parse-json/stringbuilder.c.i
.PHONY : src/parse-json/stringbuilder.c.i

src/parse-json/stringbuilder.s: src/parse-json/stringbuilder.c.s

.PHONY : src/parse-json/stringbuilder.s

# target to generate assembly for a file
src/parse-json/stringbuilder.c.s:
	$(MAKE) -f CMakeFiles/jsoncompress.dir/build.make CMakeFiles/jsoncompress.dir/src/parse-json/stringbuilder.c.s
.PHONY : src/parse-json/stringbuilder.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... jsoncompress"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/CMemLeak.obj"
	@echo "... src/CMemLeak.i"
	@echo "... src/CMemLeak.s"
	@echo "... src/json-compress/json-compress.obj"
	@echo "... src/json-compress/json-compress.i"
	@echo "... src/json-compress/json-compress.s"
	@echo "... src/json-compress/json-decompress.obj"
	@echo "... src/json-compress/json-decompress.i"
	@echo "... src/json-compress/json-decompress.s"
	@echo "... src/main.obj"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/parse-json/helpers.obj"
	@echo "... src/parse-json/helpers.i"
	@echo "... src/parse-json/helpers.s"
	@echo "... src/parse-json/json-node-ptr-list.obj"
	@echo "... src/parse-json/json-node-ptr-list.i"
	@echo "... src/parse-json/json-node-ptr-list.s"
	@echo "... src/parse-json/json-parser.obj"
	@echo "... src/parse-json/json-parser.i"
	@echo "... src/parse-json/json-parser.s"
	@echo "... src/parse-json/stringbuilder.obj"
	@echo "... src/parse-json/stringbuilder.i"
	@echo "... src/parse-json/stringbuilder.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

