node gen-list "char"
node gen-list "char*"
node gen-list "bool"
node gen-list "bool*"
node gen-list "int"
node gen-list "int *"
node gen-list "unsigned int"
node gen-list "unsigned int*"
node gen-list "short"
node gen-list "short *"
node gen-list "unsigned short"
node gen-list "unsigned short*"
node gen-list "long"
node gen-list "long *"
node gen-list "unsigned long"
node gen-list "unsigned long*"
node gen-list "float"
node gen-list "float*"
node gen-list "double"
node gen-list "double*"
node gen-list "long double"
node gen-list "long double*"